### ISSUE TITLE
今日方法有误差

### ISSUE THREAD

**Issue by RocketsChen** [chjsun/CJCalendar#2]
凌晨测试，今日方法中 获取日期不准（北京时间） -(void)DecisionDidSelectNow:(CJDecisionView *)decision{
self.Date = [NSDate dateWithTimeIntervalSinceNow:0];
}
改用 self.Date = [NSDate dateWithTimeIntervalSinceNow:[NSTimeZone systemTimeZone].secondsFromGMT]; 准确

**Comment by chjsun** [comment]
多谢
